# Optimized Cloud Build configuration for Firebase deployment
# This file defines the build and deployment pipeline for Google Cloud Build

steps:
  # Step 1: Install root dependencies
  - name: 'node:20'
    id: 'install-root-deps'
    entrypoint: 'npm'
    args: ['ci', '--prefer-offline', '--no-audit']
    timeout: 300s
    
  # Step 2: Build the React application
  - name: 'node:20'
    id: 'build-app'
    entrypoint: 'npm'
    args: ['run', 'build:production']
    env:
      - 'NODE_OPTIONS=--openssl-legacy-provider'
      - 'REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'REACT_APP_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'REACT_APP_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'
    timeout: 600s
    
  # Step 3: Deploy to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    id: 'deploy-hosting'
    args: 
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID'
    timeout: 300s
    
  # Step 4: Install functions dependencies
  - name: 'node:20'
    id: 'install-functions-deps'
    dir: 'functions'
    entrypoint: 'npm'
    args: ['ci', '--prefer-offline', '--no-audit']
    timeout: 300s
    
  # Step 5: Build Firebase Functions
  - name: 'node:20'
    id: 'build-functions'
    dir: 'functions'
    entrypoint: 'npm'
    args: ['run', 'build']
    timeout: 300s
    
  # Step 6: Deploy Firebase Functions
  - name: 'gcr.io/$PROJECT_ID/firebase'
    id: 'deploy-functions'
    args:
      - 'deploy'
      - '--only'
      - 'functions'
      - '--project'
      - '$PROJECT_ID'
      - '--force'
    timeout: 900s
    
  # Step 7: Deploy Firestore rules
  - name: 'gcr.io/$PROJECT_ID/firebase'
    id: 'deploy-firestore-rules'
    args:
      - 'deploy'
      - '--only'
      - 'firestore:rules'
      - '--project'
      - '$PROJECT_ID'
    timeout: 60s
    
  # Step 8: Deploy Storage rules
  - name: 'gcr.io/$PROJECT_ID/firebase'
    id: 'deploy-storage-rules'
    args:
      - 'deploy'
      - '--only'
      - 'storage:rules'
      - '--project'
      - '$PROJECT_ID'
    timeout: 60s

# Overall timeout for the entire build (30 minutes)
timeout: '1800s'

# Build options for optimization
options:
  # Use a more powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Disk size in GB
  diskSizeGb: 100
  
  # Logging configuration
  logging: CLOUD_LOGGING_ONLY
  
  # Enable substitution option
  substitutionOption: 'ALLOW_LOOSE'
  
  # Dynamic substitutions
  dynamic_substitutions: true

# Substitution variables
# These can be overridden at build time
substitutions:
  _FIREBASE_PROJECT_ID: 'ai-integra-course-v2'
  _FIREBASE_API_KEY: ''  # Set via Secret Manager or trigger
  _FIREBASE_AUTH_DOMAIN: 'ai-integra-course-v2.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'ai-integra-course-v2'
  _FIREBASE_STORAGE_BUCKET: 'ai-integra-course-v2.firebasestorage.app'
  _FIREBASE_MESSAGING_SENDER_ID: ''  # Set via Secret Manager or trigger
  _FIREBASE_APP_ID: ''  # Set via Secret Manager or trigger
  _FIREBASE_MEASUREMENT_ID: ''  # Set via Secret Manager or trigger

# Artifacts to store
artifacts:
  objects:
    location: 'gs://${_FIREBASE_PROJECT_ID}_cloudbuild/artifacts'
    paths:
      - 'build/**'
      - 'functions/lib/**'

# Service account to use (optional, uses default if not specified)
# serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/firebase-deploy@${PROJECT_ID}.iam.gserviceaccount.com'

# Tags for organizing builds
tags:
  - 'firebase'
  - 'production'
  - 'hosting'
  - 'functions'
